### ISSUE TITLE
Error installing rustdef 

### ISSUE THREAD

**Issue by dclong** [emakryo/rustdef#131]
Installing rustdef using the command `pip install rustdef` gives me the following error messages. I'm using Python3 3.10.6.

ERROR: Could not find a version that satisfies the requirement rustdef (from versions: none)
ERROR: No matching distribution found for rustdef

**Comment by emakryo** [comment]
I have just released rustdef v0.4.0, which contains support for Python 3.10.
Could you try reinstalling it?

**Comment by dclong** [comment]
It works! Thank you so much for the awesome tool!
